version: 2.1

workflows:
  myWorkflow:
    jobs:
      - build:
          context:
            - docker

jobs:
  build:
    docker:
      - image: cimg/python:3.9.5
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          TEST_DATABASE_URL: circleci://postgres@localhost:5432/postgres_test
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      - image: circleci/postgres:13.3
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: postgres_test
          POSTGRES_PASSWORD: ""
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    steps:
      - checkout
      - run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt update
          sudo apt install postgresql-client-12
      - run: |          
          dockerize -wait tcp://localhost:5432 -timeout 3m
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name text COLLATE "ja-x-icu");"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test (name) VALUES ('舟木'), ('森本'), ('ローズ'), ('ズーバー');"
      - run:
          psql \ 
          -d $TEST_DATABASE_URL \
          -C "SELECT * from test ORDER BY name COLLATE "ja-x-icu";"
