version: 2.1

workflows:
  myWorkflow:
    jobs:
      - build:
          context:
            - docker

jobs:
  build:
    docker:
      - image: cimg/python:3.9.5
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          LANG: UTF8
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
      - image: circleci/postgres:13.3-ram
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          LANG: UTF8
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt update
          sudo apt install postgresql-client-12
      - run: |
          dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test (name) VALUES ('Masahiko'), ('Kensuke'), ('Jim');"
      - run:
          psql \ 
          -d $TEST_DATABASE_URL \
          -C "SELECT * from test;"
