version: 2.1

workflows:
  myWorkflow:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.9.5
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:12.7-ram
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: sudo apt install postgresql-client-12.7
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test (name) VALUES ('Masahiko'), ('Kensuke'), ('Jim');"
      - run:
          psql \ 
          -d $TEST_DATABASE_URL \
          -C "SELECT * from test;"